name: Mirror to Codeberg

on:
  push:
    branches:
      - 'main'

jobs:
  mirror:
    if: ${{ secrets.MIRROR_SSH_KEY != '' }}
    runs-on: node-alpine

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H -t rsa codeberg.org >> ~/.ssh/known_hosts
          
      - name: Checkout code
        uses: https://git.pals.gay/internal/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          
      - name: Get branch name
        id: branch-name
        run: |
          echo "branch=$(git rev-parse --abbrev-ref HEAD)" >> $FORGEJO_OUTPUT
        
      - name: Configure remote
        run: |
          git remote add codeberg ssh://git@codeberg.org/fulmine/pluralkit-xyz.git
          git fetch codeberg

      - name: Push to Codeberg
        run: |
          git push -f codeberg ${{ steps.branch-name.outputs.branch }}